import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MyApp from "./app";
import { Providers } from "@/store/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <MyApp>{children}</MyApp>
        </Providers>
      </body>
    </html>
  );
}